android/app/src/main/java/com/now/naaga/data/remote/dto/DestinationDto.kt, android/app/src/main/java/com/now/naaga/data/remote/dto/PositionDto.kt
- closed: #17 
추정 시간: 30m  
실제 시간: 30m  
=> [AN] feat: DTO 생성

backend/src/main/java/com/now/naaga/NaagaApplication.java, backend/src/main/java/com/now/naaga/auth/application/AuthService.java, backend/src/main/java/com/now/naaga/auth/presentation/AuthenticationArgumentResolver.java, backend/src/main/java/com/now/naaga/common/config/WebConfig.java, backend/src/main/java/com/now/naaga/game/application/GameService.java, backend/src/main/java/com/now/naaga/game/domain/Game.java, backend/src/main/java/com/now/naaga/game/presentation/GameController.java, backend/src/main/java/com/now/naaga/game/presentation/dto/PlaceResponse.java, backend/src/main/java/com/now/naaga/game/repository/GameRepository.java, backend/src/main/java/com/now/naaga/member/application/MemberService.java, backend/src/main/java/com/now/naaga/member/persistence/repository/MemberRepository.java, backend/src/main/java/com/now/naaga/place/application/PlaceService.java, backend/src/main/java/com/now/naaga/place/persistence/repository/PlaceRepository.java, backend/src/main/resources/application.properties, backend/src/main/resources/data.sql
- closed: #14 
저의 masterpiece 입니다. 감사합니다.
- `Position` 이 VO인데, 이에 대한 DTO를 만들 필요가 있을까?
- DTO 패키지를 어디에 넣어야 할까?
추정 시간:  2시간
실제 시간:  5시간
이유:
- 거리 계산 실수 오차때문에 SQL 쿼리를 최적화해야했는데, 너무 어려웠다.
- JPQL 문법이 익숙하지 않았따.
=> [BE] feat: 장소 추천 기능 구현

android/app/src/main/java/com/now/naaga/data/repository/MockDestinationRepository.kt, android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureActivity.kt, android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureFactory.kt, android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureViewModel.kt, android/app/src/main/res/layout/activity_on_adventure.xml, android/app/src/main/res/values/strings.xml, android/domain/src/main/java/com/now/domain/model/Destination.kt, android/domain/src/main/java/com/now/domain/repository/DestinationRepository.kt
- closed: #32 
추정 시간: 1h 30m  
실제 시간: 2h
=> [AN] feat: 목적지와 현재위치 사이 거리를 계산하여 사용자에게 보여주는 기능 구현

android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureActivity.kt
- closed: #33 
추정 시간: 40m  
실제 시간: 30m
=> [AN] feat: 목적지를 마커로 표시하는 기능 구현

.github/workflows/backend_dev_ci_workflow.yml
- closed: #49  
추정 시간:   30분
실제 시간:   30분
=> [BE] feat: 백엔드 ci workflows 초안 작성

.github/workflows/backend_dev_ci_workflow.yml
- closed: #49  
추정 시간:   30분
실제 시간:   30분
=> [BE] fix: 백엔드 ci workflows 초안 작성

.github/workflows/backend_dev_ci_workflow.yml
- closed: #49  
추정 시간:   30분
실제 시간:   30분
=> [BE] fix: working directory 상대경로로 변경

android/app/build.gradle, android/app/src/main/AndroidManifest.xml, android/app/src/main/java/com/now/naaga/data/NaagaThrowable.kt, android/app/src/main/java/com/now/naaga/data/mapper/CoordinateMapper.kt, android/app/src/main/java/com/now/naaga/data/remote/dto/FailureDto.kt, android/app/src/main/java/com/now/naaga/data/remote/retrofit/RetrofitFactory.kt, android/app/src/main/java/com/now/naaga/data/remote/retrofit/RetrofitUtil.kt, android/app/src/main/java/com/now/naaga/data/repository/DefaultAdventureRepository.kt, android/app/src/main/java/com/now/naaga/data/repository/MockAdventureRepository.kt, android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureActivity.kt, android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureViewModel.kt, android/domain/src/main/java/com/now/domain/repository/AdventureRepository.kt
- closed: #45 
- enqueue를 커스텀한 fetchNaagaResponse 함수에 이상이 없는지 봐주세요
- 에러 처리 부분을 처음 만들어봐서 다들 보고 의견 말해주면 좋습니다!
추정 시간:   1h
실제 시간:   3h
이유: 에러 처리가 처음이라 많은 시간이 소요됨
=> [AN] feat: 서버에 모험 시작을 요청하는 기능 구현

android/app/src/main/java/com/now/naaga/data/remote/retrofit/service/AdventureService.kt, android/app/src/main/java/com/now/naaga/data/repository/DefaultAdventureRepository.kt
- closed: #30 
추정 시간: 1h  
실제 시간: 3h  
게임을 시작할 때 시작되지 않은 상태라면 잘 진행되지만 시작 되어있는 상태인 경우 게임이 종료되어야만 새로운 게임이 진행할 수 있는 부분을 추가적으로 해결해야 한다.
깃 충돌 해결 이슈
=> [AN] feat: 서버에서 목적지를 받아오는 기능 구현

android/app/src/main/java/com/now/naaga/data/remote/dto/EndedAdventureDto.kt, android/app/src/main/java/com/now/naaga/data/remote/retrofit/service/AdventureService.kt, android/app/src/main/java/com/now/naaga/data/repository/DefaultAdventureRepository.kt
- close: #55 
추정 시간:  30m
실제 시간:  20m
=> [AN] fix: 목적지 도착 버튼 클릭 시 발생하는 오류 수정

android/app/build.gradle, android/app/google-services.json, android/build.gradle
- closed: #74 
안드로이드 프로젝트에 firebase 추가
추정 시간: 1h  
실제 시간: 20m
=> [AN] feat: 안드로이드 프로젝트에 firebase 추가

android/app/src/main/java/com/now/naaga/presentation/upload/UploadActivity.kt
- closed: #70 
- 구현하면서 **현재 위치 좌표가 과연 사용자에게 보여져야 하는 정보일까?** 라는 의문이 들었어요. 이 부분은 어떻게 생각하시나요?
-  현재 좌표를 받아오는 것이 뷰모델에 있어야 할까에 대해 고민했는데요, 현재 좌표를 받아오기 위해서는 권한이 부여되었는지 필수로 확인해야 합니다. 이를 위해서는 Context가 필요하구요. 그래서 뷰모델보단 액티비티에 있는 것이 맞다는 판단을 했어요. 어덯게 생각하시나요?
추정 시간: 3h  
실제 시간: 2h  
이유: 이전에 학습했던 부분이기 때문에 조금 더 빨리 구현할 수 있었네요 🙃
=> [AN] feat: 디바이스의 위치를 받아와 뷰에 보여주는 기능 구현

android/app/src/main/java/com/now/naaga/data/remote/retrofit/service/StatisticsService.kt
- closed: #99 
추정 시간:  20m 
실제 시간:  10m
=> [AN] feat: 통계 path 레트로핏 서비스 구현

android/app/src/main/java/com/now/naaga/data/remote/retrofit/service/Adventure2Service.kt
- closed: #96 
추정 시간:   30m
실제 시간:   30m
=> [AN] feat: 게임 path 레트로핏 서비스 구현

android/app/src/main/java/com/now/naaga/data/remote/retrofit/service/PlaceService.kt
- closed: #97 
- multipart 부분은 확인해보니까 바이너리 파일로 들어가는 것 같아요.
- 네이밍이 통일되었나 확인해주시면 좋을 것 같아요.
- 장소를 등록하는 함수에서 PlaceDto와 MultipartBody.Part 하나씩 들어가도 될지 확인해주세요.
추정 시간: 30m  
실제 시간: 30m
=> feat: 장소 path 레트로핏 서비스 구현

android/app/src/main/java/com/now/naaga/data/mapper/PlayerMapper.kt, android/app/src/main/java/com/now/naaga/data/mapper/RankMapper.kt, android/app/src/main/java/com/now/naaga/data/remote/retrofit/ServicePool.kt, android/app/src/main/java/com/now/naaga/data/remote/retrofit/service/RankService.kt, android/app/src/main/java/com/now/naaga/data/repository/DefaultRankRepository.kt, android/domain/src/main/java/com/now/domain/repository/RankRepository.kt
- closed: #107 
enqueue로 코드 중복 없이 잘 구현이 되었는지 궁금합니다.
추정 시간: 1h  
실제 시간: 30m
=> [AN] feat: RankRepository 생성

android/app/src/main/java/com/now/naaga/data/mapper/StatisticsMapper.kt, android/app/src/main/java/com/now/naaga/data/remote/dto/third/StatisticsDto.kt, android/app/src/main/java/com/now/naaga/data/remote/retrofit/ServicePool.kt, android/app/src/main/java/com/now/naaga/data/remote/retrofit/service/StatisticsService.kt, android/app/src/main/java/com/now/naaga/data/repository/DefaultStatisticsRepository.kt, android/domain/src/main/java/com/now/domain/model/Statistics.kt, android/domain/src/main/java/com/now/domain/repository/StatisticsRepository.kt
- closed: #108 
enqueue로 코드 중복 없이 잘 구현이 되었는지 궁금합니다.
추정 시간: 30m
실제 시간: 20m
=> [AN] feat: StatisticsRepository 생성

android/app/src/main/java/com/now/naaga/data/mapper/AdventureMapper.kt, android/app/src/main/java/com/now/naaga/data/mapper/AdventureResultMapper.kt, android/app/src/main/java/com/now/naaga/data/mapper/HintMapper.kt, android/app/src/main/java/com/now/naaga/data/mapper/PlaceMapper.kt, android/app/src/main/java/com/now/naaga/data/mapper/PlayerMapper.kt, android/app/src/main/java/com/now/naaga/data/remote/retrofit/RetrofitUtil.kt, android/app/src/main/java/com/now/naaga/data/remote/retrofit/ServicePool.kt, android/app/src/main/java/com/now/naaga/data/repository/DefaultAdventureRepository.kt, android/app/src/main/java/com/now/naaga/data/repository/ThirdDemoAdventureRepository.kt, android/domain/src/main/java/com/now/domain/model/AdventureResultType.kt, android/domain/src/main/java/com/now/domain/model/OrderType.kt, android/domain/src/main/java/com/now/domain/model/SortType.kt, android/domain/src/main/java/com/now/domain/repository/AdventureRepository2.kt, android/domain/src/main/java/com/now/domain/repository/OrderType.kt, android/domain/src/main/java/com/now/domain/repository/SortType.kt
- closed: #105 
OrderType, SortType이 새로 생겼습니다.
서버에서 받아온 AdventureResultType이 우리의 enum으로 파싱에 실패했을 때 NONE 형식으로 저장됩니다.
AdventureResultType을 presentation 단에서 사용하시는 분은 이에 유의하여 오류 처리 부탁드립니다.
추정 시간: 1h
실제 시간: 1h
=> feat: 3차 데모데이 기획 변경에 맞는 AdventureRepository 설계 및 구현

android/app/src/main/java/com/now/naaga/data/mapper/PlaceMapper.kt, android/app/src/main/java/com/now/naaga/data/remote/retrofit/ServicePool.kt, android/app/src/main/java/com/now/naaga/data/repository/DefaultPlaceRepository.kt, android/domain/src/main/java/com/now/domain/repository/PlaceRepository.kt
- closed: #104 
Multipart 부분이 조금 헷갈리네요. 추후에 서버 연동하면서 알맞게 다시 처리하도록 하겠습니다.
추정 시간: 1h  
실제 시간: 3h  
이유: Multipart형태로 Place정보도 넘겨줘야 하는데 어떤 방식으로 할지 고민하다가 생각보다 늦었음
=> [AN] feat: PlaceRepository 생성

android/app/src/main/java/com/now/naaga/StatisticsMockWeb.kt
- closed: #115 
추정 시간:  2h 
실제 시간:  1h
=> [AN] feat: 통계 path api 목서버 구현

android/app/src/main/java/com/now/naaga/RankMockWeb.kt
- closed: #113 
추정 시간: 2h  
실제 시간: 1h
=> [AN] feat: 랭크 path api 목서버 구현

android/app/src/main/java/com/now/naaga/presentation/upload/UploadActivity.kt, android/app/src/main/res/layout/activity_upload.xml
- closed: #69 
추정 시간: 1h 30m  
실제 시간: 2h
=> [AN] feat: 카메라로 찍은 사진을 뷰에 띄우고 Uri 추출기능 구현

backend/src/main/java/com/now/naaga/auth/application/AuthService.java, backend/src/main/java/com/now/naaga/auth/infrastructure/BasicAuthenticationExtractor.java, backend/src/main/java/com/now/naaga/auth/presentation/AuthInterceptor.java, backend/src/main/java/com/now/naaga/auth/presentation/AuthenticationArgumentResolver.java, backend/src/main/java/com/now/naaga/game/application/FindGameByIdCommand.java, backend/src/main/java/com/now/naaga/game/application/GameService.java, backend/src/main/java/com/now/naaga/game/application/dto/CreateGameCommand.java, backend/src/main/java/com/now/naaga/game/application/dto/FindGameByStatusCommand.java, backend/src/main/java/com/now/naaga/game/application/dto/FinishGameCommand.java, backend/src/main/java/com/now/naaga/game/domain/Game.java, backend/src/main/java/com/now/naaga/game/presentation/GameController.java, backend/src/main/java/com/now/naaga/game/presentation/dto/CoordinateRequest.java, backend/src/main/java/com/now/naaga/game/presentation/dto/CreateGameRequest.java, backend/src/main/java/com/now/naaga/game/presentation/dto/FinishGameRequest.java, backend/src/main/java/com/now/naaga/game/presentation/dto/GameResponse.java, backend/src/main/java/com/now/naaga/member/presentation/dto/MemberAuthRequest.java, backend/src/main/java/com/now/naaga/player/application/PlayerService.java, backend/src/main/java/com/now/naaga/player/exception/PlayerException.java, backend/src/main/java/com/now/naaga/player/exception/PlayerExceptionType.java, backend/src/main/java/com/now/naaga/player/persistence/repository/PlayerRepository.java, backend/src/main/java/com/now/naaga/player/presentation/dto/PlayerRequest.java
- closed: #125
- GameSevrcie에서 MemberService에 의존하는 Service 로직을 PlayerService 의존하도록 변경하였습니다.
- 위 과정을 진행하며, Command와 Request DTO 분리를 하였습니다. 이를 중점으로 봐주세요
추정 시간:   3시간
실제 시간:   2시간
이유: 엄청난 페어 프로그래밍
=> [BE] feat: 3차 데모데이 뼈대 코드 추가

.github/workflows/backend_dev_pr_workflow.yml
- closed: #128
추정 시간:   30m
실제 시간:   30m
=> [BE] refactor: Pull Request 워크플로우 수정

backend/src/main/java/com/now/naaga/game/application/GameService.java, backend/src/main/java/com/now/naaga/game/application/dto/FindGameByIdCommand.java, backend/src/main/java/com/now/naaga/game/presentation/GameController.java, backend/src/main/java/com/now/naaga/game/presentation/dto/GameResponse.java, backend/src/main/java/com/now/naaga/game/presentation/dto/GameStatusResponse.java, backend/src/main/java/com/now/naaga/member/application/dto/MemberCommand.java, backend/src/main/java/com/now/naaga/place/presentation/dto/PlaceResponse.java
- closed: #135 
추정 시간: 10분
실제 시간: 10분
=> [BE] refactor: DTO들이 모두 record로 구현되도록 수정

.github/workflows/backend_dev_merge_workflow.yml, backend/Dockerfile
=> [BE] 백엔드 CD 워크플로우 수정

backend/src/main/java/com/now/naaga/common/config/WebConfig.java, backend/src/main/resources/data.sql
- closed: #160 
추정 시간:   5분
실제 시간:   5분
=> [BE] fix: 인터셉터 패턴 추가(#160)

android/app/src/main/java/com/now/naaga/presentation/adventureresult/AdventureResultActivity.kt, android/app/src/main/java/com/now/naaga/presentation/beginadventure/BeginAdventureActivity.kt, android/app/src/main/java/com/now/naaga/presentation/mypage/MyPageActivity.kt, android/app/src/main/java/com/now/naaga/presentation/splash/SplashActivity.kt, android/app/src/main/res/values/strings.xml
- closed: #144 
앱 전체적으로 연결해놨으니 확인해보시고 이상한거 말해주세요
추정 시간:  2h 
실제 시간:  1h
=> [AN] feat: 게임 시작 화면 기능 구현

android/app/build.gradle, android/build.gradle
- closed: #169 
추정 시간: 30m
실제 시간: 30m
=> [AN] feat: firebase crashlytics 초기 환경 설정

android/app/build.gradle, android/app/src/main/java/com/now/naaga/data/firebase/analytics/AnalyticsDelegate.kt, android/app/src/main/java/com/now/naaga/data/firebase/analytics/ButtonNames.kt, android/app/src/main/java/com/now/naaga/data/firebase/analytics/ServerErrorNames.kt
- closed: #165 
그.. 우리가 버튼 이벤트 로그를 클릭리스너에 심어야되면서, 해당 로그가 필요한 버튼이면 데이터바인딩 onClick을 사용할 수 없게 되었습니다. 데이터 바인딩을 사용하면서 심으려면 onClick이 호출하는 뷰모델 함수에 삽입하는 수밖에..
추정 시간:   2h
실제 시간:   4h
adb관련해서 사소한 오류가 시간을 끔, 논의하는데 생각보다 오래걸림.
=> [AN] feat: Firebase Analytics 생성 및 로그 삽입을 위한 객체 구현

backend/src/main/resources/application-test.yml, backend/src/main/resources/application.properties
- closed: #173 
추정 시간:   10분
실제 시간:   10분
=> [BE] fix: application.properties 복구

backend/src/main/resources/data.sql
- closed: #175 
추정 시간:   10분
실제 시간:   10분
=> [BE] chore: 인메모리 더미 데이터 추가

backend/src/main/java/com/now/naaga/player/domain/Rank.java, backend/src/main/java/com/now/naaga/player/presentation/dto/RankResponse.java, backend/src/test/java/com/now/naaga/player/application/PlayerServiceTest.java, backend/src/test/java/com/now/naaga/player/presentation/PlayerControllerTest.java
- 리뷰 포인트
추정 시간:   1시간
실제 시간:   1시간
=> [BE] refactor: RankReponse 수정

.github/workflows/android_ci.yml, android/app/build.gradle, android/app/src/main/java/com/now/naaga/data/remote/retrofit/RetrofitFactory.kt
- closed: #180 
추정 시간:   1h
실제 시간:   1h
=> [AN] feat: baseUrl 변경 및 감추기와 그에 따른 yml 파일 변경

backend/src/main/java/com/now/naaga/game/application/GameService.java, backend/src/main/java/com/now/naaga/player/domain/Rank.java, backend/src/main/java/com/now/naaga/player/presentation/PlayerController.java, backend/src/main/java/com/now/naaga/player/presentation/dto/RankResponse.java, backend/src/test/java/com/now/naaga/player/application/PlayerServiceTest.java, backend/src/test/java/com/now/naaga/player/presentation/PlayerControllerTest.java
리뷰시 중점적으로 봐주었으면 좋을 부분을 적어주세요.  
없다면 적지 않아도 됩니다.  
- 리뷰 포인트
추정 시간:  30분
실제 시간:   30분
=> [BE] refactor: 쿼리와 uri 수정

android/app/src/main/java/com/now/naaga/data/remote/retrofit/service/PlaceService.kt, android/app/src/main/java/com/now/naaga/data/repository/DefaultPlaceRepository.kt, android/app/src/main/java/com/now/naaga/presentation/upload/UploadActivity.kt, android/app/src/main/java/com/now/naaga/presentation/upload/UploadFactory.kt, android/app/src/main/java/com/now/naaga/presentation/upload/UploadViewModel.kt, android/app/src/main/res/layout/activity_upload.xml, android/domain/src/main/java/com/now/domain/repository/PlaceRepository.kt
- closed: #127 
업로드 뷰 기능 구현
- 현재 멀티파트 부분이 서버와 연동되지 않아서 100% 동작한다고 장담할 수 없을 것 같아요. 서버가 띄워진 후에 가장먼저 확인하고 수정하도록 할게요.
추정 시간: 4h  
실제 시간: 4h
=> [AN] feat: 업로드 뷰 기능 구현

backend/src/main/java/com/now/naaga/game/application/GameService.java, backend/src/main/java/com/now/naaga/game/application/dto/FindAllGamesCommand.java, backend/src/main/java/com/now/naaga/game/presentation/GameController.java
- closed: #185 
추정 시간:  20m
실제 시간:  20m
=> [BE] fix: GET /games 쿼리 스트링 없어도 되도록 수정

backend/src/main/java/com/now/naaga/player/presentation/PlayerController.java
리뷰시 중점적으로 봐주었으면 좋을 부분을 적어주세요.  
없다면 적지 않아도 됩니다.  
- 리뷰 포인트
추정 시간:   10분
실제 시간:   10분
=> [BE] fix: 랭크 전체조회 쿼리 파라미터 조건 수정

backend/src/main/java/com/now/naaga/game/application/dto/CreateGameCommand.java, backend/src/main/java/com/now/naaga/game/presentation/GameController.java, backend/src/test/java/com/now/naaga/game/presentation/GameControllerTest.java
리뷰시 중점적으로 봐주었으면 좋을 부분을 적어주세요.  
없다면 적지 않아도 됩니다.  
- 리뷰 포인트
추정 시간:   10분
실제 시간:   10분
=> [BE] refactor: 게임 시작 요청의 requestbody 수정

backend/src/main/java/com/now/naaga/game/application/dto/CreateHintCommand.java, backend/src/main/java/com/now/naaga/game/presentation/GameController.java, backend/src/main/java/com/now/naaga/game/presentation/dto/GameResultResponse.java, backend/src/test/java/com/now/naaga/game/presentation/GameControllerTest.java
- closed: #194 
추정 시간:   10m
실제 시간:   10m
=> [BE] fix: POST /games/{gameId}/hints 쿼리 스트링 없어도 되도록 수정

.github/workflows/backend_dev_merge_workflow.yml, .gitmodules, backend/build.gradle
- closed: #222 
추정 시간:   6h
실제 시간:   18h
=> [BE] refactor: dev 서버 환경 구축

.github/workflows/backend_dev_merge_workflow.yml
- closed: #237 
추정 시간:   10
실제 시간:   10
=> [BE] fix: 깃허브 액션 워크플로우 수정

android/app/src/main/java/com/now/naaga/data/remote/dto/AdventureDto.kt, android/app/src/main/java/com/now/naaga/data/remote/dto/AdventureResultDto.kt, android/app/src/main/java/com/now/naaga/data/remote/dto/AdventureStatusDto.kt, android/app/src/main/java/com/now/naaga/data/remote/dto/CoordinateDto.kt, android/app/src/main/java/com/now/naaga/data/remote/dto/EndedAdventureDto.kt, android/app/src/main/java/com/now/naaga/data/remote/dto/FailureDto.kt, android/app/src/main/java/com/now/naaga/data/remote/dto/FinishGameDto.kt, android/app/src/main/java/com/now/naaga/data/remote/dto/HintDto.kt, android/app/src/main/java/com/now/naaga/data/remote/dto/NaagaAuthDto.kt, android/app/src/main/java/com/now/naaga/data/remote/dto/PlaceDto.kt, android/app/src/main/java/com/now/naaga/data/remote/dto/PlatformAuthDto.kt, android/app/src/main/java/com/now/naaga/data/remote/dto/PlayerDto.kt, android/app/src/main/java/com/now/naaga/data/remote/dto/RankDto.kt, android/app/src/main/java/com/now/naaga/data/remote/dto/StatisticsDto.kt
- closed: #244 
틀린거 없나 봐주세요
추정 시간:   30m
실제 시간:   30m
=> [AN] feat: 난독화를 위해 모든 Dto 필드에 SerialName 추가

android/app/src/main/java/com/now/naaga/presentation/adventureresult/AdventureResultActivity.kt
- closed: #254 
추정 시간:  30m 
실제 시간:  10m
=> [AN] fix: 메인으로 돌아갈 시 해당 액티비티가 사라지도록 수정

android/app/src/main/java/com/now/naaga/presentation/beginadventure/BeginAdventureActivity.kt
- closed: #257 
추정 시간:  1h 
실제 시간:  30m
=> [AN] feat: 사용자가 GPS 기능을 껐을 때 이를 인지하고 키도록 유도하는 기능 구현

android/app/src/main/AndroidManifest.xml, android/app/src/main/java/com/now/naaga/NaagaApplication.kt
- closed: #249 
추정 시간:   30m
실제 시간:   30m
=> [AN] feat: 장치 구성 변경 대응

android/app/build.gradle, android/app/proguard-rules.pro
- closed: #251 
추정 시간: 30m  
실제 시간: 1h  
firebase analytics 난독화에 빠져서 헤어나오지 못했어요...
=> feat: 난독화 방지를 위한 ProGuard 수정

backend/src/main/java/com/now/naaga/game/domain/Game.java, backend/src/main/java/com/now/naaga/place/domain/Position.java, backend/src/test/java/com/now/naaga/game/domain/GameTest.java, backend/src/test/java/com/now/naaga/game/presentation/StatisticControllerTest.java
- closed: #219 
추정 시간:  30m
실제 시간:   30m
=> [BE] refactor: 좌표 간 거리를 M 단위로 변경 및 힌트/시도횟수 변경

android/app/src/main/java/com/now/naaga/data/firebase/analytics/ServerErrorNames.kt, android/app/src/main/java/com/now/naaga/presentation/adventureresult/AdventureResultActivity.kt, android/app/src/main/java/com/now/naaga/presentation/adventureresult/AdventureResultViewModel.kt, android/app/src/main/java/com/now/naaga/presentation/login/LoginActivity.kt, android/app/src/main/java/com/now/naaga/presentation/login/LoginViewModel.kt, android/app/src/main/java/com/now/naaga/presentation/mypage/MyPageActivity.kt, android/app/src/main/java/com/now/naaga/presentation/mypage/MyPageViewModel.kt, android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureActivity.kt, android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureViewModel.kt, android/app/src/main/java/com/now/naaga/presentation/rank/RankActivity.kt, android/app/src/main/java/com/now/naaga/presentation/rank/RankViewModel.kt
- closed:  #233 
- 전체적으로 잘 적용이 되었는 지 확인해주세요
추정 시간:  2h 
실제 시간:  1h
=> [AN] feat: Firebase Analytics 서버 통신 에러 로그 추가

backend/src/main/java/com/now/naaga/common/exception/ControllerExceptionHandler.java, backend/src/main/resources/logback-spring.xml
- closed: #267 
추정 시간:  1h
실제 시간:  1h
=> [BE] feat: 로깅 기능 추가

android/app/src/main/java/com/now/naaga/util/KakaoLoginUtil.kt
- closed: #270 
추정 시간: 20m  
실제 시간: 10m
=> [AN] feat: 로그인 시 사용자의 토큰이 로그에 보여지지 않도록 수정

android/app/src/main/java/com/now/naaga/presentation/beginadventure/BeginAdventureActivity.kt, android/app/src/main/java/com/now/naaga/presentation/login/LoginActivity.kt, android/app/src/main/java/com/now/naaga/presentation/splash/SplashActivity.kt
- closed: #272 
추정 시간: 10min  
실제 시간: 10min
=> [AN] feat: 스플래시에서 받아온 게임을 넘겨주는 기능 삭제

android/app/build.gradle
- closed: #289 
추정 시간:  10m 
실제 시간:  15m
=> [AN] feat: 버전 변경

.github/workflows/android_ci.yml
- closed: #310 
추정 시간:  10m 
실제 시간:  10m
=> refactor: 안드로이드 ci branch 수정

android/app/src/main/java/com/now/naaga/data/remote/retrofit/service/RankService.kt, android/app/src/main/java/com/now/naaga/data/repository/DefaultRankRepository.kt, android/app/src/main/java/com/now/naaga/presentation/adventureresult/AdventureResultViewModel.kt, android/app/src/main/java/com/now/naaga/presentation/mypage/MyPageViewModel.kt, android/app/src/main/java/com/now/naaga/presentation/rank/RankViewModel.kt, android/app/src/main/java/com/now/naaga/util/ResponseUtil.kt, android/domain/src/main/java/com/now/domain/repository/RankRepository.kt
- closed: #309 
네트워크 작업 코루틴으로 변경
추정 시간: 1h  
실제 시간: 2h
=> refactor: 네트워크 작업 코루틴으로 변경

.gitignore
=> refactor: remote top level에 필요없는 .idea 파일 삭제 및 .gitignore 추가

android/app/src/main/java/com/now/naaga/data/remote/retrofit/service/PlaceService.kt, android/app/src/main/java/com/now/naaga/data/remote/retrofit/service/StatisticsService.kt, android/app/src/main/java/com/now/naaga/data/repository/DefaultPlaceRepository.kt, android/app/src/main/java/com/now/naaga/data/repository/DefaultStatisticsRepository.kt, android/app/src/main/java/com/now/naaga/presentation/mypage/MyPageViewModel.kt, android/app/src/main/java/com/now/naaga/presentation/upload/UploadViewModel.kt, android/domain/src/main/java/com/now/domain/repository/PlaceRepository.kt, android/domain/src/main/java/com/now/domain/repository/StatisticsRepository.kt
- closed: #322 
MyPage 뷰에서 진행하는 네트워크 작업 코루틴으로 변경
코루틴 변경 사항
추정 시간: 1h  
실제 시간: 30m
=> refactor: my page뷰에서 진행하는 네트워크 작업 코루틴으로 변경

android/app/build.gradle, android/app/src/test/java/com/now/naaga/RankViewModelTest.kt, android/app/src/test/java/com/now/naaga/getOrAwaitValue.kt
- closed: #334 
추정 시간:  1h 
실제 시간:  1h
=> feat: RankViewModel 테스트 추가

backend/src/main/java/com/now/naaga/place/domain/PlaceRecommendService.java, backend/src/test/java/com/now/naaga/place/service/PlaceServiceTest.java
- closed: #384 
테스트 시 값을 어떻게 넣을지 감이 잘안와서
러프하게 루터회관 주변으로 테스트했습니다
추정 시간:   5분
실제 시간:   30분
이유: 테스트 작성 필요성
=> fix: 장소 추천 범위 정상화

android/app/src/main/java/com/now/naaga/presentation/upload/UploadActivity.kt
- closed: #412 
- 꼼꼼하게 처리하지 못해서 죄송합니다 🙇‍♂️
추정 시간: 5m  
실제 시간: 5m
=> feat: 업로드 화면에서 뒤로가기 기능 구현

android/app/build.gradle
- closed: #430 
- 이전에 올라가있던 앱 버전은 4였기 때문에 5로 수정했습니다.
- versionName을 "1.1.0" 으로 변경하였습니다.
- versionName의 기준은 시멘틱 버저닝에 맞춰 진행하려고 합니다. 디자인이 대폭 변경되었기 때문에 가운데 자리를 변경하였습니다.
Firebase Config 
추정 시간: 10m  
실제 시간: 10m  
=> feat: 버전코드 및 버전이름 수정

android/app/build.gradle, android/app/src/main/java/com/now/naaga/data/remote/retrofit/AuthInterceptor.kt
hotfix의 내용을 dev_android 로 머지한다.
=> hotfix: 액세스 토큰 리프레시 로직 수정

backend/src/main/java/com/now/naaga/like/application/dto/ApplyLikeCommand.java, backend/src/main/java/com/now/naaga/like/presentation/dto/ApplyPlaceLikeRequest.java
- close: #491 
API 명세에 맞추어 Request DTO 변수명을 수정합니다.
추정 시간:   10분
실제 시간:   10분
=> hotfix: PlaceLikeType 변수명을 API 명세에 맞춰 변경

.github/workflows/backend_dev_merge_workflow.yml, backend/Dockerfile-dev, backend/Dockerfile-prod, backend/src/main/java/com/now/naaga/like/presentation/dto/CheckMyPlaceLikeResponse.java
- closed: #444 
```shell
#!/bin/bash
IS_DEV1=$(docker ps | grep dev_naaga1)
DEFAULT_CONF=" /etc/nginx/nginx.conf"
MAX_RETRIES=20
check_service() {
local RETRIES=0
local URL=$1
while [ $RETRIES -lt $MAX_RETRIES ]; do
echo "Checking service at $URL... (attempt: $((RETRIES+1)))"
sleep 3
REQUEST=$(curl $URL)
if [ -n "$REQUEST" ]; then
echo "health check success"
return 0
fi
RETRIES=$((RETRIES+1))
done;
echo "Failed to check service after $MAX_RETRIES attempts."
return 1
}
if [ -z "$IS_DEV1" ];then
echo "### DEV2 => DEV1 ###"
echo "1. DEV1 이미지 받기"
docker-compose pull dev1
echo "2. DEV1 컨테이너 실행"
docker-compose up -d dev1
echo "3. health check"
if ! check_service "http://127.0.0.1:8080"; then
echo "DEV1 health check 가 실패했습니다."
exit 1
fi
echo "4. nginx 재실행"
sudo cp /etc/nginx/nginx1.conf …
```
=> feat: 데브서버 무중단 배포 파이프라인 적용

backend/src/main/java/com/now/naaga/auth/infrastructure/jwt/AuthTokenGenerator.java
`closed #501 `
리뷰시 중점적으로 봐주었으면 좋을 부분을 적어주세요.  
없다면 적지 않아도 됩니다.  
- 리뷰 포인트
추정 시간: 10분
실제 시간: 10분
=> hotfix: refreshToken 주기 변경 

android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureViewModel.kt
- closed: #508 
확실히 빨라졌어요! 속이 뻥 뚫립니다.
추정 시간:  10m 
실제 시간:  10m
=> feat: 쪽지를 불러오는 통신 주기 변경
