- android/app/src/main/java/com/now/naaga/data/mapper/AdventureMapper.kt
- android/app/src/main/java/com/now/naaga/data/remote/dto/EndedAdventureDto.kt
- android/app/src/main/java/com/now/naaga/data/remote/retrofit/service/AdventureService.kt
- android/app/src/main/java/com/now/naaga/data/repository/DefaultAdventureRepository.kt
- android/app/src/main/java/com/now/naaga/data/repository/MockAdventureRepository.kt
- android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureActivity.kt
- android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureViewModel.kt
- android/app/src/main/res/layout/activity_on_adventure.xml
- android/app/src/main/res/values/strings.xml
- android/domain/src/main/java/com/now/domain/repository/AdventureRepository.kt
- closed: #46 
- Result를 이용해 Retrofit 통신을 했습니다. 서버에서 받아오는 Dto는 새롭게 생성했지만, 이를 기존에 있던 domain 객체인 AdventureStatus로 변환시키는 mapper를 사용해 Presentation 계층에서는 status만으로 분기를 처리할 수 있도록 구현했습니다.
추정 시간:  1h
실제 시간:  1h 30m
이유: 서버에서 어떤 Dto로 데이터를 받아올 지 여러가지 방법들을 생각하느라 시간이 걸렸습니다.
> [AN] feat: 모험이 끝났을 때 서버에게 모험이 종료 됐음을 알려주는 기능 구현

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/com/now/naaga/presentation/adventurehistory/AdventureHistoryActivity.kt
- android/app/src/main/java/com/now/naaga/presentation/adventurehistory/AdventureHistoryViewModel.kt
- android/app/src/main/java/com/now/naaga/presentation/adventurehistory/recyclerview/AdventureHistoryAdapter.kt
- android/app/src/main/java/com/now/naaga/presentation/adventurehistory/recyclerview/AdventureHistoryViewHolder.kt
- android/app/src/main/res/drawable/ic_arrow.xml
- android/app/src/main/res/layout/activity_adventure_history.xml
- android/app/src/main/res/layout/item_history.xml
- android/app/src/main/res/values/strings.xml
- closed: #64 
리사이클러뷰를 사용해 모험기록을 띄워주는 뷰를 구현했습니다. 특히 ListAdapter를 사용해 아이템 변경애 용이하도록 구현했습니다. 그리고 최대한 데이터 바인딩을 사용하려고 했지만, 불가능한 부분은 viewHolder에 코드로 뷰가 변경되도록 구현하였습니다. ListAdapter는 처음 적용해 본 것이기 때문에 해당 부분들을 집중해서 봐주시면 좋을 것 같습니다. 
추정 시간: 3h  
실제 시간: 5h  
이유: 어떤 Adapter를 사용할까 생각하다가 이번에 ListAdapter를 사용해보자고 결정해, 해당 어댑터에 대한 장점과 사용법에 대해 공부하고 체화시키느라 시간이 생각보다 더 걸렸습니다.
> [AN] feat: AdventureHistoryActivity 구현

- backend/src/main/java/com/now/naaga/game/application/GameService.java
- backend/src/main/java/com/now/naaga/game/domain/Game.java
- backend/src/main/java/com/now/naaga/game/domain/GameRecord.java
- backend/src/main/java/com/now/naaga/game/domain/GameResult.java
- backend/src/main/java/com/now/naaga/game/exception/GameExceptionType.java
- backend/src/main/java/com/now/naaga/game/presentation/GameController.java
- backend/src/main/java/com/now/naaga/game/presentation/dto/CoordinateResponse.java
- backend/src/main/java/com/now/naaga/game/presentation/dto/GameDestinationResponse.java
- backend/src/main/java/com/now/naaga/game/presentation/dto/GameResultResponse.java
- backend/src/main/java/com/now/naaga/game/repository/GameRepository.java
- backend/src/main/java/com/now/naaga/game/repository/GameResultRepository.java
- backend/src/test/java/com/now/naaga/acceptance/game/GameControllerTest.java
- closed: #145 
추정 시간:   3시간
실제 시간:   3시간
> [BE] feat: 게임 결과 조회 기능 구현

- android/app/src/main/java/com/now/naaga/data/mapper/AdventureResultMapper.kt
- android/app/src/main/java/com/now/naaga/data/mapper/StatisticsMapper.kt
- android/app/src/main/java/com/now/naaga/data/remote/dto/AdventureResultDto.kt
- android/app/src/main/java/com/now/naaga/data/remote/dto/StatisticsDto.kt
- android/app/src/main/java/com/now/naaga/presentation/adventureresult/AdventureResultActivity.kt
- android/app/src/main/java/com/now/naaga/presentation/adventureresult/AdventureResultViewModel.kt
- android/app/src/main/java/com/now/naaga/presentation/mypage/MyPageMapper.kt
- android/app/src/main/res/layout/activity_adventure_result.xml
- android/app/src/main/res/values/strings.xml
- android/domain/src/main/java/com/now/domain/model/AdventureResult.kt
- android/domain/src/main/java/com/now/domain/model/Statistics.kt
- closed: #172 
지금 너무 api에 의존적인 도메인인 것 같아서 종종 현타가 오네요
나중에 도메인이 자립할 수 있도록 수정해봅시다,,
ex) AdventureResult 도메인에 startDateTime과 endDateTime이 존재하므로 playTime 필드를 지운다. (계산 가능)
그랬다면 이번 수정에서 도메인 수정을 하지 않을 수 있었겠죠?
게임 결과 뷰에서는 수정이 조금 있었지만 마이페이지에선 presentation단의 수정사항은 없었습니다. (toUi 매퍼 제외)
추정 시간:   30h
실제 시간:   1h
뷰의 수정도 추가되면서 조금 더 오래걸렸습니다.
> [AN] feat: API 수정으로 인한 변경사항 적용

- backend/src/main/java/com/now/naaga/game/application/GameService.java
- backend/src/main/java/com/now/naaga/game/presentation/GameController.java
- backend/src/main/java/com/now/naaga/game/presentation/dto/GameResultResponse.java
- backend/src/main/java/com/now/naaga/player/domain/Player.java
- backend/src/main/java/com/now/naaga/score/domain/Score.java
- closed: #197 
추정 시간:   20m
실제 시간:   20m
> [BE] feat: 게임 종료 시, 플레이어 점수 덧셈 기능 추가

- backend/src/main/java/com/now/naaga/auth/application/dto/AuthInfo.java
- backend/src/main/java/com/now/naaga/auth/infrastructure/AuthClient.java
- closed: #246 
restTemplate.postForObject()에서 JSON을 객체로 파싱하는 과정에서 기본 생성자 없어서 안됐던 부분 추가
추정 시간: 10분
실제 시간:  30분
이유: 왜 안되는지 명확히 알기 어려운 문제였다
> fix: AuthInfo에 기본 생성자 추가

- android/.editorconfig
- android/app/src/main/java/com/now/naaga/presentation/adventureresult/AdventureResultActivity.kt
- android/app/src/main/java/com/now/naaga/presentation/beginadventure/BeginAdventureActivity.kt
- android/app/src/main/java/com/now/naaga/presentation/login/LoginActivity.kt
- android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureActivity.kt
- android/app/src/main/java/com/now/naaga/presentation/splash/SplashActivity.kt
- android/app/src/main/java/com/now/naaga/presentation/splash/SplashViewModel.kt
- android/app/src/main/java/com/now/naaga/util/IntentExt.kt
- android/app/src/main/res/values/strings.xml
- closed: #248 
- 현재는 splash에서 얻어온 Adventure를 Splash > Login > BeginAdventure > OnAdventure 이렇게 넘겨주고 있어요.
- BeginAdventureActivity에서 게임의 Status로 조회를 해서 데이터가 있다면 텍스트를 '이어하기'로 바꿔줘도 되겠지만 이 경우 서버통신이 종료되기 전까지는 '모험하기' 였다가 통신이 완료되고 진행중인 게임이 있는 것을 확인하면 '이어하기'로 변경되는데 이 흐름이 굉장히 어색해요. 더 자연스러운 흐름이 있을까요?
추정 시간: 2h  
실제 시간: 4h  
- 이유 : 로직의 고민을 많이했다. 근데 결과적으로 원래대로 돌아왔다..;;
> [AN] feat: 이어하기 기능 추가

- android/app/src/main/java/com/now/naaga/data/remote/retrofit/service/PlaceService.kt
- android/app/src/main/java/com/now/naaga/data/repository/DefaultPlaceRepository.kt
- android/app/src/main/java/com/now/naaga/presentation/beginadventure/BeginAdventureActivity.kt
- android/app/src/main/java/com/now/naaga/presentation/upload/UploadActivity.kt
- android/app/src/main/java/com/now/naaga/presentation/upload/UploadViewModel.kt
- android/app/src/main/res/values/strings.xml
- closed: #286 
장소 추가 기능 구현
`@PartMap` 애노테이션을 통해 여러 개의 RequestBody를 묶어 한번에 보낼 수 있도록 기능을 구현했어요. 이런 방식으로 진행하면 POST 요청에서 서버에 보내야 하는 값이 하나 더 추가되더라도 PartMap에 추가만 해주면 되기 때문에 변경에 유연하다고 느껴집니다.
String을 RequestBody로 바꿔 HashMap에 추가하여 PlaceService의 registerPlace 함수의 인자로 넣어줘요.  
이 때 PlaceService의 PartMap의 자료형을 Map으로 두고 DefaultPlaceRepository에서는 HashMap에 넣어줘서 보내니 아래와 같은 에러가 발생하더라구요. 그래서 HashMap으로 수정해주었습니다.
| 에러 해결 방법 : https://github.com/square/retrofit/issues/3275
정확한 이유는 더 찾아봐야 함
DataThrowable로 반환된 예외 중 인증관련(200번대 에러 코드)를 잡는 UniversalThrowable과 장소관련(500번대 에러 코드)를 잡는 PlaceThrowable만을 잡아 핸들링 하도록 구현했어요.
205번 에러 : 요청 바디 값이 잘못 된 경우
215번 에러 : 사진 저장에서 문제가 생긴 경우
505번 에러 : 주변에 이미 저장된 장소가 있는 경우
위에서 잡은 예외들의 에러코드에 따라 적절한 메시지를 토스트로 띄워주도록 구현했어요.
- 적절한 에러를 적절한 방법으로 핸들링 했다고 생각하시는지 궁금합니다. 더 좋은 핸들링 방법이 있을 것 같기도 해서요! …
> feat: 장소 업로드 기능 구현

- android/app/src/main/java/com/now/naaga/presentation/beginadventure/BeginAdventureActivity.kt
- android/app/src/main/java/com/now/naaga/presentation/upload/UploadActivity.kt
- android/app/src/main/java/com/now/naaga/presentation/upload/UploadViewModel.kt
- android/app/src/main/res/layout/activity_upload.xml
- closed: #300 
기존에 LocationManager를 이용하여 위치를 가져왔었는데, 이 메서드를 통해 가져오는 위치 정보 값이 Null인 경우도 많고, 언제 업데이트 된 정보인지 알기 어려워서 FusedLocationProvider를 통해 값을 가져오는 방식으로 수정했습니다.
위치를 받아오는 메서드가 비동기로 실행되서 사용자에게 기다림이 필요하다는 것을 명시적으로 표시하기 위해 로딩 로티를 추가했어요.
ViewModel이 위치 정보를 가지고 있는 상태에요. 이렇게 구현한 이유는 위치를 가져오는 메서드가 비동기로 실행인데요. 언제 값을 가져올지 모르기 때문에 유저에게 로딩 로티를 보여주고 값을 받아오면 로티가 보이지 않도록 변경하기 위함입니다.  
그래서 로직이 좀 이상한데요. 
액티비티가 뷰모델의 위치정보를 구독한다. → 액티비티에서 현재 위치를 가져온다. → 뷰모델에 넣어준다. → 뷰모델의 데이터가 변경됨을 감지해 로티를 없애준다.  
제가 생각한 최선의 방법인데요, 빅스가 생각했을 때 더 좋은 방법이 있다면 추천해줘도 됩니다.  
그리고 현재 뷰에 좌표를 보여주는 것이 과연 사용자에게 의미있는 행동일까도 좀 고민을 해봤어요. 빅스와 이야기 나눠보고 싶네요.
추정 시간: 2h  
실제 시간: 2h
> fix: 위치관련 버그 수정

- android/app/src/main/java/com/now/naaga/presentation/upload/UploadActivity.kt
- android/app/src/main/java/com/now/naaga/presentation/upload/UploadFactory.kt
- android/app/src/main/java/com/now/naaga/presentation/upload/UploadViewModel.kt
- closed: #306 
ViewModel이 Application을 참조하지 않도록 변경을 잘 하였는가
추정 시간: 20m  
실제 시간: 20m
> refactor: ViewModel이 Application을 참조하지 않도록 변경

- android/app/src/main/java/com/now/naaga/data/remote/retrofit/service/AuthService.kt
- android/app/src/main/java/com/now/naaga/data/repository/DefaultAuthRepository.kt
- android/app/src/main/java/com/now/naaga/presentation/login/LoginActivity.kt
- android/app/src/main/java/com/now/naaga/presentation/login/LoginViewModel.kt
- android/domain/src/main/java/com/now/domain/repository/AuthRepository.kt
- closed: #326 
AuthRepository 내에서 서버 통신 시 받아온 토큰 값을 SharedPreference에 저장해야 했습니다. 따라서 레포지터리 내의 코루틴 사용이 필요해져 해당 AuthRepository 생성 시 Dispatcher을 클래스의 인자로 넘겨주도록 수정하였습니다. 해당 로직이 괜찮은 지 확인 부탁드립니다!
추정 시간:  1h 
실제 시간:  1h
> refactor: Login 뷰에서 진행하는 네트워크 작업 코루틴으로 변경

- android/app/src/main/res/layout/activity_adventure_history.xml
- android/app/src/main/res/layout/item_history.xml
- closed: #316 
이미지 설정 코드가 중복으로 들어가 있어서 해당 버그가 발생한 것 입니다. 현재 중복 로직 삭제했고 잘 돌아갑니다
추정 시간:  10m 
실제 시간:  10m
> fix: History 뷰의 리사이클러뷰 image 오류 문제 해결

- android/app/src/main/java/com/now/naaga/data/remote/retrofit/service/AdventureService.kt
- android/app/src/main/java/com/now/naaga/data/repository/DefaultAdventureRepository.kt
- android/app/src/main/java/com/now/naaga/presentation/adventurehistory/AdventureHistoryViewModel.kt
- android/app/src/main/java/com/now/naaga/presentation/adventureresult/AdventureResultViewModel.kt
- android/app/src/main/java/com/now/naaga/presentation/beginadventure/BeginAdventureViewModel.kt
- android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureViewModel.kt
- android/app/src/main/java/com/now/naaga/presentation/splash/SplashViewModel.kt
- android/domain/src/main/java/com/now/domain/repository/AdventureRepository.kt
- closed #314 
추정 시간: 1h
실제 시간:  1h
> refactor: Adventure 도메인에 해당하는 네트워크 작업 코루틴으로 변경

- android/app/build.gradle
- android/app/src/test/java/com/now/naaga/AdventureHistoryViewModelTest.kt
- android/app/src/test/java/com/now/naaga/getOrAwaitValue.kt
- closed: #339 
추정 시간:  1h 
실제 시간:  30m
> feat: AdventureHistoryViewModel 테스트 추가

- android/app/src/main/java/com/now/naaga/data/remote/retrofit/service/AuthService.kt
- android/app/src/main/java/com/now/naaga/data/repository/DefaultAuthRepository.kt
- android/app/src/main/java/com/now/naaga/presentation/login/LoginActivity.kt
- android/app/src/main/java/com/now/naaga/presentation/setting/SettingActivity.kt
- android/app/src/main/java/com/now/naaga/presentation/setting/SettingViewModel.kt
- android/app/src/main/java/com/now/naaga/util/KakaoLoginUtil.kt
- android/app/src/main/res/values/strings.xml
- android/domain/src/main/java/com/now/domain/repository/AuthRepository.kt
- closed: #329 
현재 설정 뷰에서 회원탈퇴를 누르게 되면 서버의 API와 연동 후, 해당 과정이 성공하면 카카오에게도 토큰 정보를 삭제해달라는 `unlink` 함수를 실행시키도록 구현해놓았습니다. 
그리고 만일 회원 탈퇴가 성공적으로 진행되면 회원탈퇴가 성공적으로 진행되었다는 토스트가 뜨고 로그인 페이지로 이동하도록 했습니다. 
여기서 한가지 리뷰어님께 물어보고 싶은점이 있는데, 지금은 그냥 설정뷰에서 회원탈퇴를 누르면 바로 탈퇴가 되는 중입니다. 
혹시 여기서 확인 다이얼로그를 한번 더 띄우거나 하는 추가 로직이 필요할까요? 
추정 시간:  1h 
실제 시간:  2h 
이유: API의 싱크 맞추기와 Response body가 null 값인 상황을 해결하느라 좀 더 걸렸습니다.
> feat: 회원 탈퇴 기능 구현

- android/app/build.gradle
- android/app/src/test/java/com/now/naaga/AdventureResultViewModelTest.kt
- android/app/src/test/java/com/now/naaga/getOrAwaitValue.kt
- closed: #336 
추정 시간:  1h 
실제 시간:  1h
> feat: AdventureResultViewModel 테스트 추가

- android/app/src/main/java/com/now/naaga/di/DataSourceModule.kt
- android/app/src/main/java/com/now/naaga/di/RepositoryModule.kt
- closed: #351
datasource 의존성 주입 라이브러리 적용
```kotlin
// 모듈 클래스
@Module
@InstallIn(SingletonComponent::class)
class DataSourceModule {
@Singleton
@Provides
fun provideAuthDatasource(@ApplicationContext context: Context): AuthDataSource = DefaultAuthDataSource(context)
}
// 구현체 클래스
class DefaultAuthDataSource(context: Context) : AuthDataSource
```
- 모듈을 object 혹은 class로 선언해야 합니다.
- 함수에서 직접 반환을 해주기 때문에 interface 혹은 abstract class는 선언이 불가능합니다.
- provideXxx 메서드에서 어떤 인스턴스를 어떻게 구현하여 반환할 것인지 정의되어 있기 때문에 구현체 클래스에는 변화가 없습니다.
```kotlin
// 모듈 클래스
@Module
@InstallIn(SingletonComponent::class)
abstract class DataSourceModule {
@Singleton
@Binds
abstract fun bindAuthDatasource(defaultAuthDataSource: DefaultAuthDataSource): AuthDataSource
}
// 구현체 클래스
class DefaultAuthDataSource @Inject constructor( …
```
> refactor: datasource 의존성 주입 라이브러리 적용

- backend/src/main/java/com/now/naaga/temporaryplace/domain/TemporaryPlace.java
- backend/src/main/java/com/now/naaga/temporaryplace/presentation/TemporaryPlaceController.java
- backend/src/main/java/com/now/naaga/temporaryplace/repository/TemporaryPlaceRepository.java
- closed: #372 
장소 검수 도메인과 장소 도메인의 내용이 완전히 같습니다. 따라서 `장소 검수 도메인이 기존의 place 패키지 내부에 들어가야할까?` 를 고민하게 되었는데요!
도메인의 생명주기 관점에서 보았을 때, 장소 검수 도메인의 생성/파괴 시점과 장소 도메인의 생성/파괴 시점이 서로 다릅니다.
다만, 장소 검수 후에 장소 등록 시나리오를 거쳤을 경우에는, 장소 검수 도메인의 파괴와 장소 도메인의 생성 로직이 한 트랜잭션 안에 물려야합니다.
때문에, 이 경우에는 꽤 많은 도메인 제약사항을 공유하고 있다고 생각하긴 했습니다만, 장소 검수 후 등록 반려가 되는 시나리오에서는 생명주기가 완전히 분리되어버리기 때문에.. 복합적으로 고려했을 때, 대부분의 경우에서 생명주기가 다르다고 판단, 패키지를 분리하게 되었습니다.
기존 place 테이블에 검수 flag 값을 두어서 한 테이블 안에서 관리를 할 수도 있었습니다.
다만 이럴 경우에, place 테이블 안에는 실제 인게임에서 등록된 장소와, 아직 검수가 필요한 장소가 혼재되어서 place 테이블이 비대해질 수 있다는 문제점이 존재했습니다.
실제로 우리 팀의 비즈니스 시나리오에서는, 인게임 등록 장소보다 검수가 필요한 장소의 수가 압도적으로 많습니다.
이 경우에서, 만약 인게임 등록 장소만을 조회하기 위해 place 테이블 조회 쿼리가 발생하면, 필요 이상으로 비대한 place 테이블에 대해 테이블 풀스캔이 일어나야합니다. (중복이 많기 때문에 카디널리티가 굉장히 낮으므로) 이는 인덱스로도 개선할 수 없는 문제입니다.
따라서, 검수가 필요한 장소들의 …
> feat: 장소 검수 기능 뼈대코드 설계 및 구현

- android/app/src/main/java/com/now/naaga/di/ServiceModule.kt
- closed: #371 
OkHttpClient의 interceptor를 AuthInterceptor로 변경하였고, 이 때 직접 생성하여 넣어주도록 변경했습니다. 이렇게 한 이유는 AuthInterceptor는 재사용되지 않기 때문에 힐트가 싱글턴으로 관리하고 있을 필요가 없다고 생각했어요. 이 부분에 대해 어떻게 생각하는지 남겨주시면 좋을 것 같습니다!
추정 시간: 30m  
실제 시간: 30m  
직접 작성한 코드에서 발생한 문제가 아니라서 이유를 찾는데 오래 걸렸네요..
> fix: OkHttpClient의 interceptor를 AuthInterceptor로 변경

- backend/src/main/java/com/now/naaga/game/application/GameService.java
- backend/src/main/java/com/now/naaga/gameresult/domain/GameResult.java
- backend/src/main/java/com/now/naaga/gameresult/repository/GameResultRepository.java
- backend/src/main/java/com/now/naaga/place/domain/Place.java
- backend/src/test/java/com/now/naaga/gameresult/application/GameResultServiceTest.java
- backend/src/test/java/com/now/naaga/gameresult/repository/GameResultRepositoryTest.java
- closed: #356 
1. List<Game>을 PlayerId 로 조회 : 쿼리 1번
2. List<Game>에 대한 GameResult를 각각 조회 : 쿼리 N번
3. GameResult -> GameRecord 변환 과정에서 Game의 힌트 조회 : 쿼리 N번 (GameRecord에서 힌트의 정보가 필요하기 때문)
- 예시
- 플레이어가 10번의 게임을 마쳤을때, </br> 1번의 상황으로 쿼리 1번, </br>2번의 상황으로 쿼리 10번, </br>3번의 상황으로 쿼리 10번이 발생하여</br>총 21개의 쿼리가 발생함
- 두번의 조인 쿼리문을 작성하여 게임 결과를 가져올때 게임의 대한 모든 정보(힌트까지) 모두 조회하도록 쿼리를 작성하였습니다.
추정 시간:   1시간
실제 시간:   1시간
> fix: 나의 통계 조회 시 성능 저하 문제 해결

- android/app/build.gradle
- android/app/src/main/java/com/now/naaga/common/dialog/ConfirmDialog.kt
- android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureActivity.kt
- android/app/src/main/java/com/now/naaga/presentation/splash/SplashActivity.kt
- android/app/src/main/java/com/now/naaga/util/dialog/ConfirmDialog.kt
- android/app/src/main/java/com/now/naaga/util/extension/IntentExt.kt
- android/app/src/main/java/com/now/naaga/util/extension/PackageManagerExt.kt
- android/app/src/main/res/layout/dialog_confirm.xml
- android/app/src/main/res/values/strings.xml
- closed: #370 
앱 강제 업데이트 기능 구현
- Firebase Config를 통해서 업데이트가 필요한 버전 이하인 경우 버전 업데이트를 요청하도록 구현했어요!  
- 다음과 같이 Firebase에 우리가 원하는 값들을 저장해둘 수 있습니다.
- 앱에서는 splash 화면에서 Firebase Config에 올라가있는 version과 현재 앱의 version을 비교하여 현재 앱의 버전이 더 낮은 경우 업데이트를 요청하는 다이얼로그가 뜨도록 구현했어요!
- fetchAndActivate() 메서드가 비동기적으로 동작하기 때문에 스플래시 화면이 오래 뜰 수도 있다는 단점이 있습니다.
- 갱신 주기를 3600초(1시간)으로 설정해두었기 때문에 접속한지 1시간 내에 강제 업데이트가 필요한 내용이 플레이 스토어에 업데이트가 된다면 이것도 문제가 될 수도 있을 것 같긴 해요.
- 현재 앱의 versionName을 받아오는 기능을 PackageManager 의 확장함수로 정의했습니다. 이렇게 한 이유는 버전에 따른 분기가 필요한 코드라서 그렇습니다.
- 현재 util 패키지가 꾕장히 너저분하더라고요. 그래서 패키지 정리가 필요해보이지만 현재 pr에서 작업할 것은 아니라고 생각해서 그냥 뒀습니다... 
- 인게임에서 사용하는 다이얼로그와는 다른 확인용 다이얼로그를 만들었어요. 크게 다른 것은 없지만 업데이트를 강제 해야 할 때는 다이얼로그가 Cancelable하지 않도록 만들기 위해 추가했습니다.
- 버튼 2개의 비율이 1:1 입니다.
- 만들고나니 그냥 있던 다이얼로그의 이름을 조금 수정하고 사용했어도 …
> feat: 앱 강제 업데이트 기능 구현

- android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureActivity.kt
- closed: #405
```kotlin
viewModel.hints.observe(this) { hints ->
drawHintMarkers(hints)
binding.lottieOnAdventureLoading.visibility = View.GONE
showPolaroidDialog()
}
```
- 힌트 마커들을 띄워주고, 로티를 보이지 않도록 한 다음 바로 사진 다이얼로그가 보이도록 했습니다! (실행해보면 조오오오금 어색한 감이 있긴 합니다..)
- 게임에 처음 입장할 때, 다시 입장할 때 모두 사진이 먼저 뜹니다. 재입장 시에도 매번 뜨도록 할 것인가는 논의해봐야 할 수도 있을 것 같아요. 저는 게임에 재입장 하는 경우가 흔하지 않을 것이라고 생각해서 괜찮다는 입장입니다! 생각이 어떤지 남겨주시면 좋을 것 같아요🙃
- 우리가 사용하는 다이얼로그들을 common/dialog package 하위로 이동하는 것은 어떤가요? 현재 PR과는 관련이 없다고 생각해서 의견만 남겨봅니다!
- 추가로 이름을 수정하면 더 좋을 것 같아요! 아래는 제 생각입니다.
- NaagaAlertDialog -> GameDialog (인게임에서만 사용)
- PolaroidDialog 유지 (인게임에서만 사용)
- ConfirmDialog 유지 (인게임 외에서 범용적으로 사용)
- LocationPermissionDialog(begin, upload 에서 사용), CameraPermissionDialog(upload에서만 사용) 두 개를  PermissionDialog 로 합쳐 사용하기
- 우리가 요청하는 …
> feat: 게임 입장 시 사진이 먼저 뜨는 기능 구현

- backend/src/main/java/com/now/naaga/auth/presentation/interceptor/ManagerAuthInterceptor.java
- backend/src/main/java/com/now/naaga/common/config/WebConfig.java
- backend/src/main/java/com/now/naaga/place/application/PlaceService.java
- backend/src/main/java/com/now/naaga/place/application/dto/CreatePlaceCommand.java
- backend/src/main/java/com/now/naaga/place/presentation/PlaceController.java
- backend/src/main/java/com/now/naaga/place/presentation/dto/CreatePlaceRequest.java
- backend/src/main/java/com/now/naaga/place/presentation/dto/PlaceResponse.java
- backend/src/main/java/com/now/naaga/temporaryplace/application/TemporaryPlaceService.java
- backend/src/test/java/com/now/naaga/auth/presentation/interceptor/ManagerAuthInterceptorTest.java
- backend/src/test/java/com/now/naaga/place/application/PlaceServiceTest.java
- backend/src/test/java/com/now/naaga/place/presentation/PlaceControllerTest.java
- closed: #376 
관리자 페이지에서 사용할 검수 장소 등록 허가 API 를 구현하였습니다!
먼저, 대부분의 장소 API 엔드포인트는 사용자가 주체이지만, 등록 허가에 대한 API 는 사용자가 아닌 관리자가 주체입니다.
여기서 중요한 점은, `사용자가 주체인 API 의 인가 장치는 jwt 토큰 방식`이지만, `관리자가 주체인 API 의 인가 장치는 basic 인증 방식`입니다.
따라서, 같은 엔드포인트에 대해서 서로 다른 HTTP 메서드에 따라 인터셉터도 달라져야 했습니다.
이 부분에 대한 기술적 해결 방안은 [루카 박사님의 논문](https://github.com/woowacourse-teams/2023-naaga/pull/374) 을 통해 확인하실 수 있고, 이를 이용해 서로 다른 인터셉터를 타도록 설정해두었습니다.
또한, 결정된 서비스 비즈니스 시나리오에 의하면, 관리자 페이지에서 등록 허가 버튼을 눌렀을 때 `인게임 장소에 데이터 등록 + 검수 장소에서 데이터 삭제` 라는 행위가 한번에 이루어져야합니다.
따라서 이를 구현하기 위해 하나의 트랜잭션으로 묶어 처리했습니다.
+)
ManagerAuthInterceptor 에서 Base64 디코딩하는 과정에서 로직 오류가 있어서, 이 부분을 함께 수정했습니다.
또한, 아직 검수 장소 삭제에 대한 로직이 구현되지 않은 관계로, 임시적으로 동작하지 않는 메서드를 구현해놓았습니다. 양해 부탁드립니다!
추정 시간:   4시간
실제 시간:   4시간
> feat: 검수 중인 장소에 대한 장소 등록 허가 API 구현

- backend/src/main/java/com/now/naaga/common/config/WebConfig.java
- backend/src/main/java/com/now/naaga/place/presentation/PlaceController.java
- backend/src/main/java/com/now/naaga/temporaryplace/application/TemporaryPlaceService.java
- backend/src/main/java/com/now/naaga/temporaryplace/domain/TemporaryPlace.java
- backend/src/main/java/com/now/naaga/temporaryplace/presentation/TemporaryPlaceController.java
- backend/src/test/java/com/now/naaga/common/builder/TemporaryPlaceBuilder.java
- backend/src/test/java/com/now/naaga/place/application/PlaceServiceTest.java
- backend/src/test/java/com/now/naaga/temporaryplace/application/TemporaryPlaceServiceTest.java
- backend/src/test/java/com/now/naaga/temporaryplace/presentation/TemporaryPlaceControllerTest.java
- closed: #388 
[이 PR](https://github.com/woowacourse-teams/2023-naaga/pull/398) 에 대한 연장선인 작업물입니다.
따라서, PR의 내용에 대한 맥락은 위 PR 과 같습니다. 참고해주세요!
관리자 페이지에서 사용할 승인 거절은 결국 DB 단에서의 단순 삭제 로직이라서, 크게 어려운 점은 없었던 것 같습니다.
그나마 고민했던 지점은, 검수 장소 삭제에 대해 soft delete 할 것인지, hard delete 할 것인지였는데요!
검수 장소 엔티티가 복잡한 연관관계를 가지는 것도 아니고, 검수 승인 거절을 하였는데 DB 단에 굳이 남겨서 리소스를 낭비할 필요는 없을 것 같아 hard delete 로 구현하게 되었습니다!
+)
이전 PR 브랜치에 리베이스해서 작업했더니, 커밋 내역이 같이 딸려와서 위에 커밋 범위를 남겨놓겠습니다!!
참고해서 리뷰해주시면 감사하겠습니다 😁
추정 시간:   2시간
실제 시간:   2시간
> feat: 검수 중인 장소에 대한 등록 승인 거절 API 구현

- android/app/src/main/java/com/now/naaga/presentation/setting/SettingActivity.kt
- android/app/src/main/res/values/strings.xml
- closed: #423 
- 문의하기를 누르면 이메일 창으로 이동해 공식 계정으로 이메일을 보낼 수 있도록 구현하였습니다.
- 제목도 [나아가 리뷰하기]로 지정해주었습니다.
추정 시간:  1h 
실제 시간:  1h 30m 
이유: strings 리소스가 안먹히는 안드로이드 억까를 당해서 30분 지연됨
> feat: 문의하기 기능 구현

- android/app/build.gradle
- android/app/src/main/java/com/now/naaga/data/local/DefaultAuthDataSource.kt
- android/app/src/main/java/com/now/naaga/data/remote/retrofit/AuthInterceptor.kt
- closed: #434 
액세스 토큰 리프레시 및 자동 로그인 로직 수정
- local.properties 에 등록한 BASE_URL을 마지막에 **"/" 로 끝나도록 통일시켜 주세요.**
- 이를 기반으로 모든 URL은 "/"로 시작하도록 통일하겠습니다. ex) /auth/refresh
- 앱의 버전 코드를 6으로, 버전 이름을 "1.1.1" 로 변경하였습니다. 앱이 플레이스토어에 성공적으로 배포된다면 Firebase Remote Config에 등록된 강제 업데이트 요청 최소 버전도 "1.1.1"로 변경해줘야 합니다.
- AuthInterceptor의 intercept 에서 response.code(http 상태코드)가 401인 경우 서버에서 내려주는 에러코드가 101인 경우, 102인 경우를 다음과 같이 다르기 때문에 분기처리를 진행하려고 했습니다.
- 101인 경우는 토큰 값이 잘못된 것이기 때문에 사용자에게 새로운 로그인을 요청해야 합니다. 
- 102인 경우는 액세스 토큰이 만료된 것이기 때문에 액세스 리프레시 요청을 해야 합니다.
- 하지만 Response를 한 번 DTO로 변환하게 되면 해당 Response는 Closed 되게 됩니다. 즉, 아예 사용하지 못하는 상태로 된다는 것입니다.  때문에 서버에서 내려주는 에러코드에 따라 분기처리를 진행하지 않았습니다. 
- 401에러에 대해 리프레시 요청을 진행하고, 다시 실패한 경우 에러코드가 101인 경우 AuthorizationThrowable으로 변환하여 요청에 대한 응답을 실패로 반환하기 때문에 문제가 없으리라 생각됩니다.
- 하여 조금 더 …
> hotfix: 액세스 토큰 리프레시 및 자동 로그인 로직 수정

- android/app/build.gradle
- android/app/src/main/java/com/now/naaga/data/remote/retrofit/AuthInterceptor.kt
- closed: #445 
```kotlin
private fun getAccessTokenAfterRefresh(accessToken: String): Result<String> {
val requestBody = createRefreshRequestBody()
val request = createRefreshRequest(requestBody, accessToken)
val auth: NaagaAuthDto = requestRefresh(request).getOrElse {
return Result.failure(it)
}
storeToken(auth.accessToken, auth.refreshToken)
return Result.success(BEARER + auth.accessToken)
}
```
- 함수명을 조금 더 직관적으로 변경했습니다.
- 리프레시 토큰을 통해 액세스 토큰을 갱신하고, "Bearer " 를 붙여 반환하도록 변경했습니다.
추정 시간:   
실제 시간: 3h
> hotfix: 액세스 토큰 리프레시 로직 수정

- backend/src/main/java/com/now/naaga/like/application/PlaceLikeService.java
- backend/src/test/java/com/now/naaga/like/application/PlaceLikeServiceTest.java
- closed: #472 
hotfix입니다.
지난번 [좋아요/싫어요 삭제 PR](https://github.com/woowacourse-teams/2023-naaga/pull/433)에 대한 수정입니다.
좋아요를 삭제할 때만 좋아요 개수를 한개 줄여야되는데, 
싫어요를 삭제할 때도 좋아요 개수를 한개 줄이는 오류 수정입니다.
추정 시간:  30분
실제 시간:   15분
> hotfix: 좋아요/싫어요 취소 시, 싫어요 취소해도 좋아요 통계 줄어드는 오류 수정

- backend/src/main/java/com/now/naaga/game/exception/GameExceptionType.java
- backend/src/main/java/com/now/naaga/letter/application/LetterService.java
- backend/src/main/java/com/now/naaga/letter/application/letterlog/ReadLetterLogService.java
- backend/src/main/java/com/now/naaga/letter/application/letterlog/dto/LetterLogCreateCommand.java
- backend/src/main/java/com/now/naaga/letter/exception/LetterException.java
- backend/src/main/java/com/now/naaga/letter/exception/LetterExceptionType.java
- backend/src/main/java/com/now/naaga/letter/presentation/LetterController.java
- backend/src/main/java/com/now/naaga/letter/presentation/dto/LetterReadCommand.java
- backend/src/main/java/com/now/naaga/letter/presentation/dto/LetterResponse.java
- backend/src/test/java/com/now/naaga/letter/application/LetterServiceTest.java
- backend/src/test/java/com/now/naaga/letter/application/letterlog/ReadLetterLogServiceTest.java
- backend/src/test/java/com/now/naaga/letter/presentation/LetterControllerTest.java
- backend/src/test/resources/truncate.sql
- closed: #459 
흐름은 다음과 같습니다:
1. 쪽지 아이디로 쪽지를 찾는다.
2. 플레이어를 이용해서 진행중인 게임을 찾고, 찾은 쪽지id를 readLetterLog 테이블에 insert 한다.
3. 1번에서 찾은 쪽지를 반환한다.
고민사항:
NOT_EXIST_IN_PROGRESS("진행 중인 게임이 존재하지 않습니다.") 라는 에러가 추가되었습니다.
2번 과정에서 진행중인 게임을 찾는 로직이 있는데,
만약 진행중인 게임이 없다면 그건 잘못된 요청이며, 이를 NOT_EXIST("게임이 존재하지 않습니다.") 
라는 에러로 처리할지 NOT_EXIST_IN_PROGRESS 라는 새로운 에러가 필요할지 이레와 함께 논의한 결과
둘의 상황이 다르다고 판단하였습니다.
이유는 id로 조회할때 사용하는 NOT_EXIST 와 where 절을 사용하는 상황이 다르다고 생각하였습니다.
결론은 NOT_EXIST_IN_PROGRESS을 추가하게되었는데 다른 팀원들의 의견도 궁금하군요..!
인수테스트만 작성된 상태입니다. api 구현이 모두 끝나고 리뷰 받으면서 단위테스트를 추가하겠습니다..!
제가 마음이 급해서..양해 부탁합니다!
추정 시간:   2h분
실제 시간:   2.5h분
> feat: 쪽지 단건 조회 api 구현

- android/app/src/main/res/layout/activity_adventure_result.xml
- closed: #500
- 본인 휴대폰에서 실행 한 번만 확인해주세용!
추정 시간: 30m  
실제 시간: 20m
> fix: 게임 결과 뷰에서 뷰들이 겹치는 문제 해결

- android/app/src/main/res/layout/item_letter.xml
- closed: #506 
추정 시간: 20m  
실제 시간: 20m
> fix: 쪽지가 긴 경우 보이지 않는 경우 해결

- android/app/build.gradle
- android/app/src/main/res/values/strings.xml
- closed: #520 
- 사용자가 사용하다가 크래시가 나는지 확인하기 위해 release 모드에서만 동작하도록 했습니다. 실제로 배포한 뒤에 Crashlytics를 확인했는데 저희가 개발하면서 들어온 문제도 포함되어 있어서 보기가 어렵더군요.
- 앱 라이브러리 종속 항목의 미사용 리소스를 포함하여 패키징된 앱에서 사용하지 않는 리소스를 삭제합니다. 리소스 축소는 코드 축소와 함께 사용하여 미사용 코드를 삭제하고 마찬가지로 더 이상 참조되지 않는 리소스도 안전하게 삭제할 수 있습니다.
추정 시간: 1h  
실제 시간: 1h  
> feat: 앱 gradle 설정 변경

- android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureActivity.kt
- android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureViewModel.kt
- closed: #543 
- `OnAdventure`의 `handleGameThrowable`에서 `_throwable.value = throwable` 설정을 해주지 않아 남은 시도 횟수 알림이 보이지 않던 것 이였습니다. 지금은 throwable 을 설정해주어 throwable의 옵저버가 해당 변화를 인식하고 그때에 맞게 남은 횟수 토스트를 띄워 줍니다.
- 기존에는 알림이 snackbar 형태였었는데 토스트로 변경하였습니다. 개인적 취향으로 스낵바 보다 토스트가 더 눈에 띄더라고요... 리뷰어님의 의견도 궁금합니다! 기존 스낵바 형태로 유지하는게 좋을까요?
추정 시간:  1h 
실제 시간:  2h 
이유: 어디가 문제인지 몰라서 빙글빙글 코드 타고타고 돌고돌고 돌아다니는 여정이 생각보다 길어져서 시간이 오래 걸렸습니다.
> refactor: 도전 실패 반응 확인 기능 구현

- android/app/src/main/java/com/now/naaga/presentation/common/dialog/LetterSendDialog.kt
- android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureActivity.kt
- android/app/src/main/res/values/strings.xml
- closed: #521 
- 토스트 문구가 괜찮은지 궁금합니다.
추정 시간:  1h
실제 시간:  1h 
> feat: 빈 쪽지 못남기게 하는 기능 구현
